USE ECOMMERCE
GO
-- Quantos pedidos foram feitos por cada cliente?
SELECT 
	CONCAT(FNAME, ' ', MINIT, ' ', LNAME) AS Cliente, 
	COUNT(*) AS 'Quantidade de pedidos' 
FROM CLIENTS WITH(NOLOCK)
	INNER JOIN ORDERS WITH(NOLOCK) ON IDORDERCLIENT = IDCLIENT
GROUP BY FNAME, MINIT, LNAME, IDORDERCLIENT HAVING COUNT(*) >= 1
ORDER BY CLIENTE DESC

-- Algum vendedor também é fornecedor?
SELECT 
	COUNT(*) AS 'Quantidade de vendedores que também são fornecedores' 
FROM SELLER SEL WITH(NOLOCK)
	INNER JOIN SUPPLIER SUP WITH(NOLOCK) ON SEL.CNPJ = SUP.CNPJ

-- Relação de produtos, fornecedores e estoques;
SELECT 
	PNAME AS Produto, 
	PS.QUANTITY AS 'Unidades no Estoque',
	CONCAT(SL.LOCATION, ' - ', PS.STORAGELOCATION) AS 'Localização do Estoque', 
	SU.SOCIALNAME AS Fornecedor,
	SU.CONTACT as 'Contato do Fornecedor',
	SU.CNPJ AS CNPJ,
	PSU.QUANTITY as 'Unidades no Fornedor'
FROM PRODUCT P
	INNER JOIN STORAGELOCATION SL ON P.IDPRODUCT = SL.IDLPRODUCT
	INNER JOIN PRODUCTSTORAGE PS ON PS.IDPRODSTORAGE = SL.IDLSTORAGE
	INNER JOIN PRODUCTSUPPLIER PSU ON P.IDPRODUCT = PSU.IDPSPRODUCT
	INNER JOIN SUPPLIER SU ON SU.IDSUPPLIER = PSU.IDPSSUPPLIER
ORDER BY Produto ASC

-- Relação de nomes dos fornecedores e nomes dos produtos;
SELECT 
	PNAME AS Produto, 
	SU.SOCIALNAME AS Fornecedor,
	SU.CONTACT as 'Contato do Fornecedor',
	SU.CNPJ AS CNPJ
FROM PRODUCT P
	INNER JOIN PRODUCTSUPPLIER PSU ON P.IDPRODUCT = PSU.IDPSPRODUCT
	INNER JOIN SUPPLIER SU ON SU.IDSUPPLIER = PSU.IDPSSUPPLIER
ORDER BY PRODUTO


--Relação cliente e formas de pagamento.
SELECT 
	CONCAT(CLI.FNAME, ' ', CLI.MINIT, ' ', CLI.LNAME) AS Cliente,
	CLI.ADDRESS AS 'Endereço',
	PAY.TYPEPAYMENT AS 'Tipo de Pagamento',
	CP.CARDNAME AS 'Nome no Cartão',
	CP.CARDNUMBER AS 'Número do Cartão',
	CP.CPF AS 'CPF Informado no Cartão',
	CP.EXPIRATIONDATE AS 'Data de Validade do Cartão'
FROM CLIENTS CLI
	INNER JOIN PAYMENT PAY ON PAY.IDCLIENT = CLI.IDCLIENT
	INNER JOIN CARDPAYMENT CP ON CP.IDCARDPAYMENT = PAY.IDCARDPAYMENT 
WHERE 
	ADDRESS LIKE 'RUA%'
	AND CP.EXPIRATIONDATE >= '20240101'
ORDER BY 2 ASC


--Relação Cliente , Pedido e Entrega.
SELECT 
	CONCAT(FNAME, ' ', MINIT, ' ', LNAME) AS Cliente,
	ADDRESS AS 'Endereço',
	DELIVERYSTATUS AS Rastreio,
	SENTVALUE AS Frete
FROM CLIENTS
	INNER JOIN ORDERS ON IDCLIENT = IDORDERCLIENT
	INNER JOIN DELIVERY ON IDDORDER = IDORDER
WHERE 
	ORDERSTATUS = 'Em Processamento'
	AND SENTVALUE > 0